# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='plan',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='place',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='trip.User'),
            preserve_default=False,
        ),
    ]
