# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20180626_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='trip.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_members',
            field=models.ManyToManyField(related_name='joined_trips', to='trip.User'),
        ),
    ]
