# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='We are red', max_length=255),
            preserve_default=False,
        ),
    ]
