# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to='app1.User')),
                ('jobsadded', models.ManyToManyField(related_name='joined_jobs', to='app1.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_members',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
